# Generated by Django 5.0.8 on 2024-08-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='mic',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='Ticker',
        ),
    ]
