# Generated by Django 5.0.8 on 2024-08-30 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('tickers', '0003_rename_company_ticker_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ticker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tickers.ticker'),
        ),
    ]
