# Generated by Django 5.0.8 on 2024-09-02 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_ticker'),
        ('tickers', '0004_alter_ticker_company_name_alter_ticker_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, help_text='Company Name', max_length=50, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ticker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='tickers.ticker'),
        ),
    ]
