# Generated by Django 5.0.8 on 2024-08-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='company',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='symbol',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
