# Generated by Django 5.0.8 on 2024-08-29 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0002_alter_ticker_company_alter_ticker_symbol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticker',
            old_name='company',
            new_name='company_name',
        ),
    ]
